const {test}=require('node:test');
const assert=require('node:assert/strict');
const fs=require('node:fs');
const path=require('node:path');
const os=require('node:os');
const net=require('node:net');
const {once}=require('node:events');
const {spawn}=require('node:child_process');
const {JSDOM,VirtualConsole}=require('jsdom');
async function eventually(condition,message) {
  const until=Date.now()+5000;
  while(Date.now()<until){if(condition())return;await new Promise(r=>setTimeout(r,20));}
  assert.fail(message);
}
test('client flow: recovery screen, household portions, edit/reuse, plan wizard, preferences and progress',async(t)=>{
  const root=path.resolve(__dirname,'..'),temp=fs.mkdtempSync(path.join(os.tmpdir(),'nutrilog-client-'));
  const socket=net.createServer();socket.listen(0,'127.0.0.1');await once(socket,'listening');const port=socket.address().port;await new Promise(r=>socket.close(r));
  const stub=path.join(temp,'provider.cjs');
  fs.writeFileSync(stub,`global.fetch=async()=>new Response(JSON.stringify({choices:[{message:{content:JSON.stringify({reply:'Try a bowl of dal with your lunch. <script>bad()</script>'})}}]}));`);
  const server=spawn(process.execPath,['--require',stub,'server.js'],{cwd:root,env:{...process.env,PORT:String(port),HOST:'127.0.0.1',DATA_DIR:temp,DATABASE_URL:'',POSTGRES_URL:'',VERCEL:'',GROQ_API_KEY:'fake',ADMIN_EMAIL:'nobody@example.test'},stdio:['ignore','pipe','pipe']});
  t.after(async()=>{if(server.exitCode===null){server.kill();await once(server,'exit');}fs.rmSync(temp,{recursive:true,force:true});});
  await new Promise((resolve,reject)=>{const timer=setTimeout(()=>reject(new Error('Server startup timeout')),5000);server.stdout.once('data',()=>{clearTimeout(timer);resolve();});});
  const base=`http://127.0.0.1:${port}`,errors=[];
  function client(file,token,phone=false){
    const virtualConsole=new VirtualConsole();virtualConsole.on('jsdomError',error=>{if(!/navigation/.test(error.message))errors.push(error.message);});
    const dom=new JSDOM(fs.readFileSync(path.join(root,file),'utf8'),{url:base+(file==='dashboard.html'?'/dashboard':'/'),runScripts:'outside-only',pretendToBeVisual:true,virtualConsole});
    t.after(()=>dom.window.close());
    const w=dom.window;w.fetch=(route,options)=>fetch(base+route,options);
    const phoneMedia=new w.EventTarget();phoneMedia.matches=phone;
    w.matchMedia=query=>query.includes('max-width: 600px')?phoneMedia:{matches:false};
    const viewport=new w.EventTarget();viewport.height=844;viewport.offsetTop=0;Object.defineProperty(w,'visualViewport',{value:viewport});
    w.scrollTo=(options)=>{if(options?.behavior && !['auto','smooth'].includes(options.behavior))throw new TypeError('Unsupported ScrollBehavior');};w.structuredClone=structuredClone;
    if(token)w.localStorage.setItem('diet-session-token-v1',token);
    const files=file==='dashboard.html'?['nutrition.js','planner.js','app.js','product.js','ai-client.js']:['app.js','product.js'];
    w.eval(files.map(f=>fs.readFileSync(path.join(root,f),'utf8')).join('\n')+'\nwindow.__test={get state(){return state;},analyzeMealText,showSection,loadDashboardData,render};');
    return {w,viewport,phoneMedia,q:s=>w.document.querySelector(s),input(s,value){const el=w.document.querySelector(s);el.value=value;el.dispatchEvent(new w.Event('input',{bubbles:true}));},submit(s){w.document.querySelector(s).dispatchEvent(new w.Event('submit',{bubbles:true,cancelable:true}));}};
  }
  const auth=client('index.html');auth.q('#show-signup-btn').click();
  auth.input('#signup-email','client@example.test');auth.input('#signup-password','test-password');auth.input('#signup-confirm-password','test-password');auth.submit('#signup-form');
  await eventually(()=>auth.q('#signup-recovery-output code'),'Recovery code should be shown after signup');
  assert.equal(auth.q('#signup-form [type="submit"]').disabled,true);
  auth.q('#signup-recovery-output .primary-btn').click();assert.equal(auth.q('#login-form').classList.contains('auth-form-hidden'),false);
  auth.q('#show-reset-btn').click();assert.equal(auth.q('#reset-password-form').classList.contains('app-hidden'),false);
  auth.q('#back-login-btn').click();
  const login=await (await fetch(base+'/api/auth/login',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({email:'client@example.test',password:'test-password'})})).json();
  const app=client('dashboard.html',login.token),{q,w}=app;
  await eventually(()=>w.__test.state.currentUser && q('#summary-status').textContent==='Not logged','Dashboard should finish loading');
  const theme=w.document.createElement('style');theme.textContent=fs.readFileSync(path.join(root,'styles.css'),'utf8');w.document.head.append(theme);
  assert.equal(w.getComputedStyle(q('#toast')).pointerEvents,'none','An invisible toast must not intercept mobile navigation taps');
  q('#toast').classList.add('visible');assert.equal(w.getComputedStyle(q('#toast')).pointerEvents,'auto','Visible toast actions remain clickable');q('#toast').classList.remove('visible');
  for (const section of ['add-meal','diet-plan','progress','dashboard']) {
    q(`.mobile-bottom-nav [data-section="${section}"]`).click();
    assert.equal(q('.app-section.active').id,`section-${section}`,'Mobile navigation must switch the visible screen');
    assert.equal(q(`.mobile-bottom-nav [data-section="${section}"]`).getAttribute('aria-current'),'page');
  }
  assert.equal(q('#usuals-panel').classList.contains('app-hidden'),true);
  q('[data-open-section="add-meal"]').click();app.input('#meal-description','2 rotis, 1 katori dal, 1 bowl rice');q('#analyze-meal-btn').click();
  await eventually(()=>q('#meal-calories').value==='607','Food estimate should populate macros');assert.ok(q('#meal-name').value);
  q('[data-portion="0.5"]').click();assert.equal(q('#meal-calories').value,'304');assert.equal(w.__test.state.formIngredients[0].grams,40);
  app.submit('#meal-form');await eventually(()=>w.__test.state.meals.length===1,'Meal should persist');
  assert.equal(q('#summary-status').textContent,'Day in progress');assert.equal(q('.ring-val').textContent,'304');
  q('.favorite-btn').click();await eventually(()=>w.__test.state.favorites.length===1,'Favourite should persist');
  q('.edit-btn').click();await eventually(()=>w.__test.state.editingMealId,'Edit should load original meal');
  q('#analyze-meal-btn').click();await eventually(()=>q('#meal-calories').value==='303','Recalculation should preserve the saved half portion');
  app.input('#meal-name','Edited meal');app.submit('#meal-form');await eventually(()=>w.__test.state.meals[0].name==='Edited meal' && !w.__test.state.editingMealId,'Edit should replace rather than duplicate');assert.equal(w.__test.state.meals.length,1);
  q('[data-open-section="add-meal"]').click();q('#favorite-list button[aria-label^="Log "]').click();await eventually(()=>w.__test.state.meals.length===2,'Quick log should add one meal');
  w.__test.showSection('diet-plan');
  for(const [id,value] of [['current-weight','75'],['target-weight','70'],['height','175'],['age','25']])app.input('#plan-'+id,value);
  const next=q('.wizard-nav-row .primary-btn');next.click();assert.equal(q('#plan-form .plan-fieldset').disabled,true);next.click();
  assert.equal(q('#plan-form [type="submit"]').closest('.plan-actions').style.display,'');app.submit('#plan-form');
  await eventually(()=>w.__test.state.plan,'Plan should save');assert.equal(w.__test.state.goals.calories,w.__test.state.plan.calculated.targetCalories);
  const goals=await (await fetch(base+'/api/goals',{headers:{Authorization:`Bearer ${login.token}`}})).json();assert.equal(goals.goals.calories,w.__test.state.goals.calories);
  w.__test.showSection('settings');app.input('#profile-name','Test person');app.input('#profile-allergies','peanuts');q('#profile-diet').value='vegetarian';app.submit('#profile-form');
  await eventually(()=>q('#profile-feedback').textContent.includes('saved'),'Preferences should save');assert.equal(w.__test.state.profile.allergies,'peanuts');
  w.__test.showSection('progress');app.input('#weight-kg','75.2');app.submit('#weight-form');await eventually(()=>w.__test.state.weights.length===1,'Weight should save');
  app.input('#weight-date','2020-01-01');app.input('#weight-kg','78');app.submit('#weight-form');await eventually(()=>w.__test.state.weights.length===2,'Second check-in should save');assert.ok(q('.weight-chart'));
  assert.match(q('#progress-stats').textContent,/1\/7 days/);assert.match(q('#weekly-chart').textContent,/Not logged/);
  await w.__test.loadDashboardData();w.__test.render();assert.equal(w.__test.state.profile.displayName,'Test person');assert.equal(w.__test.state.plan.goal,'cutting');
  assert.equal(q('#coach-widget').classList.contains('app-hidden'),true);
  assert.equal(q('#coach-launcher').classList.contains('app-hidden'),false);
  q('#coach-launcher').click();
  assert.equal(q('#coach-widget').classList.contains('app-hidden'),false);
  assert.equal(q('#coach-launcher').getAttribute('aria-expanded'),'true');
  assert.equal(w.__test.state.activeSection,'progress','Opening chat must keep the current page');
  app.input('#chat-input','Draft to keep');
  w.document.dispatchEvent(new w.KeyboardEvent('keydown',{key:'Escape',bubbles:true}));
  assert.equal(q('#coach-widget').classList.contains('app-hidden'),true);
  assert.equal(w.document.activeElement,q('#coach-launcher'));
  q('#coach-launcher').click();assert.equal(q('#chat-input').value,'Draft to keep');
  await eventually(()=>!q('#chat-send').disabled,'Conversation should load');
  q('[data-chat-prompt]').click();assert.match(q('#chat-input').value,/improve/);
  app.submit('#chat-form');q('#chat-close').click();
  await eventually(()=>q('.chat-assistant'),'Coach should reply');
  assert.equal(q('#coach-widget').classList.contains('app-hidden'),true);
  assert.equal(q('#coach-launcher').classList.contains('has-reply'),true);
  q('#coach-launcher').click();assert.equal(q('#coach-launcher').classList.contains('has-reply'),false);
  assert.equal(q('#chat-messages').querySelector('script'),null,'AI text must never execute HTML');
  assert.equal(q('#chat-input').value,'');
  app.input('#chat-input','How much dal?');app.submit('#chat-form');await eventually(()=>q('#chat-messages').querySelectorAll('.chat-message').length===4 && !q('#chat-send').disabled,'Follow-up should preserve turns');
  const reloaded=client('dashboard.html',login.token);
  await eventually(()=>reloaded.q('#chat-messages').querySelectorAll('.chat-message').length===4,'Chat should survive page reload');
  reloaded.q('#coach-launcher').click();
  reloaded.q('#chat-clear').click();assert.equal(reloaded.q('#chat-clear-confirm').classList.contains('app-hidden'),false);
  reloaded.q('#chat-confirm-clear').click();await eventually(()=>reloaded.q('#chat-status').textContent==='Fresh conversation ready.','New chat should clear saved history');
  assert.equal(reloaded.q('#chat-messages').querySelectorAll('.chat-message').length,0);
  q('#chat-close').click();w.__test.showSection('dashboard');q('.discuss-btn').click();
  assert.equal(w.__test.state.activeSection,'dashboard');assert.equal(q('#coach-widget').classList.contains('app-hidden'),false);
  assert.ok(q('#chat-input').value.includes(w.__test.state.meals[0].name));
  const phone=client('dashboard.html',login.token,true);
  await eventually(()=>phone.w.__test.state.currentUser && !phone.q('#chat-send').disabled,'Phone conversation should load');
  phone.q('#coach-launcher').click();
  assert.equal(phone.q('#coach-widget').getAttribute('aria-modal'),'true');
  assert.equal(phone.w.document.activeElement,phone.q('#chat-close'),'Opening on a phone should not force the keyboard open');
  assert.equal(phone.q('#app-shell').hasAttribute('inert'),true);
  assert.equal(phone.q('.mobile-bottom-nav').hasAttribute('inert'),true);
  phone.input('#chat-input','Phone draft');
  const enter=new phone.w.KeyboardEvent('keydown',{key:'Enter',bubbles:true,cancelable:true});phone.q('#chat-input').dispatchEvent(enter);
  assert.equal(enter.defaultPrevented,false,'Phone return key should allow a new line; the Send button sends');
  phone.viewport.height=360;phone.viewport.offsetTop=42;phone.viewport.dispatchEvent(new phone.w.Event('resize'));phone.viewport.dispatchEvent(new phone.w.Event('scroll'));
  assert.equal(phone.q('#coach-widget').style.getPropertyValue('--chat-viewport-height'),'360px');
  assert.equal(phone.q('#coach-widget').style.getPropertyValue('--chat-viewport-top'),'42px');
  assert.equal(phone.q('#coach-widget').classList.contains('chat-compact'),true);
  assert.equal(phone.q('#chat-input').value,'Phone draft');
  phone.phoneMedia.matches=false;phone.phoneMedia.dispatchEvent(new phone.w.Event('change'));
  assert.equal(phone.q('#coach-widget').getAttribute('aria-modal'),'false');assert.equal(phone.q('#app-shell').hasAttribute('inert'),false);
  phone.phoneMedia.matches=true;phone.phoneMedia.dispatchEvent(new phone.w.Event('change'));
  phone.q('#chat-close').click();
  assert.equal(phone.q('#app-shell').hasAttribute('inert'),false);assert.equal(phone.w.document.body.classList.contains('coach-chat-open'),false);
  assert.equal(phone.w.document.activeElement,phone.q('#coach-launcher'));
  phone.q('#coach-launcher').click();assert.equal(phone.q('#chat-input').value,'Phone draft');
  phone.viewport.height=844;phone.viewport.offsetTop=0;phone.viewport.dispatchEvent(new phone.w.Event('resize'));
  assert.equal(phone.q('#coach-widget').classList.contains('chat-compact'),false);
  assert.deepEqual(errors,[],'No unhandled client errors');
});
